### ISSUE TITLE
配置好后无法连接

### ISSUE THREAD

**Issue by Hitouo** [Tremb1e/ucas_ipv6_bypass#2]
按照教程一步步配置好以后，还是无法连接到境外服务器
![image](https://user-images.githubusercontent.com/80233758/156368348-70d27c6c-9cb0-4912-bff7-e283232f4e64.png)
![image](https://user-images.githubusercontent.com/80233758/156368428-374c353a-d224-4989-a1e1-3e156f8e4697.png)
能不能线下帮助不TnT

**Comment by Hitouo** [comment]
![image](https://user-images.githubusercontent.com/80233758/156370644-65d642bc-ca10-4379-a4fd-8bec21582afc.png)

**Comment by Tremb1e** [comment]
嗯嗯，可以的。我明天会去图书馆，可以给我的邮箱发你的联系方式。

**Comment by Tremb1e** [comment]
最后一张图看起来应该是连接成功了，如果还有疑问可以在群里加我微信。如果不知道我是谁可以发我邮箱你的联系方式。

**Comment by Tremb1e** [comment]
> ![image](https://user-images.githubusercontent.com/80233758/156370644-65d642bc-ca10-4379-a4fd-8bec21582afc.png)

这一张图看起来应该是连接成功了，如果还有疑问可以在群里加我微信。如果不知道我是谁可以发我邮箱你的联系方式。

**Comment by Hitouo** [comment]
不知道你的邮箱是多少，你直接加我微信18990980389

**Comment by Hitouo** [comment]
> > ![图片](https://user-images.githubusercontent.com/80233758/156370644-65d642bc-ca10-4379-a4fd-8bec21582afc.png)
> 
> 这图看起来应该是连接成功了，如果还有疑问可以在群里加我微信。如果不是我发信箱我知道你的联系方式。

不知道你的邮箱是什么，你直接加我微信吧18990980389
