### ISSUE TITLE
手机不能使用

### ISSUE THREAD

**Issue by Cai-Yao** [Tremb1e/ucas_ipv6_bypass#3]
你好，我电脑上成功连接了，但是我在手机上通过二维码配置了shadowsocks，但是所有的应用都不可以使用，不知道是不是还需要配置一些什么

**Comment by Tremb1e** [comment]
> 你好，我电脑上成功连接了，但是我在手机上通过二维码配置了shadowsocks，但是所有的应用都不可以使用，不知道是不是还需要配置一些什么



> 你好，我电脑上成功连接了，但是我在手机上通过二维码配置了shadowsocks，但是所有的应用都不可以使用，不知道是不是还需要配置一些什么

1.ssr客户端中填写的服务器ip地址应为ipv6地址
2.ssr客户端中路由设置为“绕过局域网地址”
3.ssr客户端中打开ipv6路由和udp转发
4.ssr客户端中设置为全局代理
5.如果还不行，多次重新连接WiFi尝试
6.我自己是一直可以使用的（安卓）

**Comment by Cai-Yao** [comment]
好的，我去试试
